### PR TITLE
Add meson build system

### PR DESCRIPTION
**Pull request by gasinvein**
This allows building zypak with meson. Potentially it could allow more flexible build-time configuration, but in scope of this PR only basic build was added. Tested with Chrome and VSCode.

### CODE REVIEW

**Comment by refi64** [comment]
Hmm, I'm not entirely sure about this...

The main (admittedly selfish) reason I used `make` initially was so that I could have working auto-complete when my editor was running in a different environment than the build. I use VSCode in a container rather than the Flatpak for various reasons (most notably, having the OS be consistent with my host system means I can take core dumps from the host and debug them in the container easily), and currently I can run `make compile_flags.txt` on the host to have a list of compile flags in sync with the Flatpak ones. Now with Meson I could technically just generate one build directory for the Flatpak environment and another for my container environment, but it's still a bit messier to keep things updated. (I also personally don't like some aspects of Meson, though really they're relatively minor, and I'm not one to complain given the current system involves over 70 lines of Makefile macros...)

Normally I do hate Makefile-based systems for...a lot of reasons, but Zypak is still relatively small and doesn't really require any fancy configurations, the most I do is occasionally use the address sanitizer. Plus, we get a...almost non-existent bonus of not having to specify `buildsystem: meson`. Well, that bonus sounded a lot cooler in my head at least.

All this being said, I'm not *particularly* against switching build systems, I'd just want there to be some tangible gain from it. Was there some particular compile-time configuration you had in mind when you opened this? (I'm also aware I could just leave both build systems in place, but that goes back to the "tangible gain" part: keeping both of them up-to-date without a clear reason wouldn't be that great.)

**Comment by gasinvein** [comment]
> bonus of not having to specify `buildsystem: meson`.

I guess we can put `exec meson . _flatpak_build "$@"` to the `configure` script (and `ninja ...` to `Makefile`, if we are to drop the current one)?

> Was there some particular compile-time configuration you had in mind when you opened this?

I thought `ZYPAK_BIN` and `ZYPAK_LIB` vars could be either compiled-in, or the wrapper could be configured at build time with proper values.

**Comment by refi64** [comment]
> I thought `ZYPAK_BIN` and `ZYPAK_LIB` vars could be either compiled-in, or the wrapper could be configured at build time with proper values.

Ah, the reason the wrapper detects this at runtime is so that you can run Zypak without installation, i.e. `./zypak-wrapper.sh ...` from the source directory after it's been built. *Technically* we could drop this, and just have the Makefile create an output directory structure that mimics /app...but it probably be a tad bit messier and I'm not sure if it would be worth it. Unfortunately Meson wouldn't fix this, afaik it's decently strict about the output directory layout (at least from some limited previous experience)?

**Comment by gasinvein** [comment]
Hmm, why even need to run it directly from build directory? If those vars are compiled-in, you can just build _and install_ zypak with some in-tree prefix, e.g. `$(pwd)/build-prefix`, and run zypak as `./build-prefix/bin/zypak-helper`.
Well, at least it's what I usually do with meson/cmake-based projects.

**Comment by refi64** [comment]
I've been debating this for a while now, but I do think I'm going to leave it as-is. Juggling multiple build prefixes and install local dirs is just a bit painful, and it tends to be moreso when testing with multiple runtime versions and such. Given that that's the *only* reason for build-time configuration for now (and probably for a long time), I don't feel this is worth the change.

**Pull request closed without merging**
